def addval = "http://192.168.53.153"

pipeline {
    agent any
    environment {
       add = 'http://192.168.53.153'                               //can be used in whole pipeline
    }
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
 	
        stage('Deploy in Staging Environment'){
            steps{
		//sh '/opt/tomcat/tomcat-prodth/bin/shutdown.sh;  /opt/tomcat/tomcat-ups/bin/startup.sh  '
		sh '''
			if [ $(curl -sw '%{http_code}' "${env.add}":9091 | tail -c 3) -eq '200' ]; then /opt/tomcat/tomcat-prodth/bin/shutdown.sh; fi
  			if [ $(curl -sw '%{http_code}' "$(env.add)":9091 | tail -c 3) -eq '200' ]; then /opt/tomcat/tomcat-prodth/bin/shutdown.sh; fi
			if [ `curl -sw '%{http_code}' "${env.add}" | tail -c 3` -eq '200' ]; then /opt/tomcat/tomcat-prodth/bin/shutdown.sh; fi
		  	if [ `curl -sw '%{http_code}' ${env.add}:9090 | tail -c 3` -eq '000' ]; then /opt/tomcat/tomcat-ups/bin/startup.sh ; fi	
		'''
                build job: 'Deploy_App_Staging'

            }
            
        }
	
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
		sh '''
                        if [ `curl -sw '%{http_code}' http://add:9090 | tail -c 3` -eq '200' ]; then /opt/tomcat/tomcat-ups/bin/shutdown.sh; fi
			if [ `curl -sw '%{http_code}' http://add:9090 | tail -c 3` -eq '404' ]; then /opt/tomcat/tomcat-ups/bin/shutdown.sh; fi
			if [ `curl -sw '%{http_code}' http://add:9090 | tail -c 3` -eq '500' ]; then /opt/tomcat/tomcat-ups/bin/shutdown.sh; fi
                        if [ `curl -sw '%{http_code}' http://add:9091 | tail -c 3` -eq '000' ]; then /opt/tomcat/tomcat-prodth/bin/startup.sh ; fi
                '''

                build job: 'Deploy_App_Prod'
            }
        }
    }
}
