pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f java-tomcat-sample/pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            }
        }
        stage('Deploy in Staging Environment'){
            steps{
		//sh '/opt/tomcat/tomcat-prodth/bin/shutdown.sh;  /opt/tomcat/tomcat-ups/bin/startup.sh'
		sh '''
			/opt/tomcat/tomcat-prodth/bin/startup.sh
			/opt/tomcat/tomcat-prodth/bin/shutdown.sh
			/opt/tomcat/tomcat-ups/bin/startup.sh
		'''
                build job: 'Deploy_Application_Staging_Env'

            }
            
        }
        stage('Deploy to Production'){
            steps{
                timeout(time:5, unit:'DAYS'){
                    input message:'Approve PRODUCTION Deployment?'
                }
		sh '/opt/tomcat/tomcat-ups/bin/startup.sh; /opt/tomcat/tomcat-ups/bin/shutdown.sh;  /opt/tomcat/tomcat-prodth/bin/startup.sh'
                build job: 'Deploy_Application_Prod_Env'
            }
        }
    }
}
